#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Local 2 ULN Sync"
echo "</title></head><body>"
echo "<center><u><h2>Generating system information for the host $(hostname -s)</h2></u></center>"
echo ""
echo "<pre> $(sleep 3) </pre>"
echo "<h3>Memory Info:</h3>"
echo "<pre> $(free -m) </pre>"
echo "<pre> $(sleep 3) </pre>"
echo "<h3>Disk Info:</h3>"
echo "<pre> $(df -h) </pre>"
echo "<pre> $(sleep 3) </pre>"
echo "<h3>Logged in user:</h3>"
echo "<pre> $(w) </pre>"
echo "<pre> $(sleep 3) </pre>"
echo "<h3> Sync Log history:</h3>"
echo "<pre> $(cat /var/log/cron* | grep uln-yum-mirror) </pre>"
echo "<h1>Initiating Sync with Oracle ULN...</h1>"
echo "<h3>Sync is in Process, please be patient as it may take a while..Please keep this session opened until you get a notification!!!!</h3>"
echo "<pre> $(sleep 3) </pre>"
echo "<h3> The yum sync job is being pushed to background, You can close this tab.</h3>"
echo "<center>Information generated on $(date)</center>"
echo "<pre> $(sudo /usr/bin/uln-yum-mirror &) </pre>"
echo "</body></html>"
